# Generated by Django 5.1 on 2024-08-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0005_profile_bio_profile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
